language: ruby
cache: bundler
rvm:
  - 2.5.0
env:
  - DB=sqlite
script: 
  - bundle exec rake db:create db:migrate
  - RAILS_ENV=test bundle exec rake
bundler_args: --without production
addons:
    code_climate:
        repo_token: c65ad213f7d077571907e7395684d2367c127165c7928191d07aff726a65bd15
after_success:
  - bundle exec codeclimate-test-reporter
